### ISSUE TITLE
After installation, clean cache, logout _ Fatal error: Class 'Mage_Ho_Euromail_Helper_Data' not found

### ISSUE THREAD

**Issue by shirtsofholl** [ho-nl/Ho_Customer#1]
Fatal error: Class 'Mage_Ho_Euromail_Helper_Data' not found in /home/shirts350/domains/domain.com/public_html/app/Mage.php on line 568

Magento 1.9.0.1

Installed via MODMAN

**Comment by paales** [comment]
@shirtsofholl Fixed in https://github.com/ho-nl/Ho_Customer/commit/c977dcf400857f405335524bb0fbd047386c5495
