### ISSUE TITLE
Error when customer tries to create an account /w HO Customer already made account

### ISSUE THREAD

**Issue by seansan** [ho-nl/Ho_Customer#3]
Error when customer tries to create an account /w HO Customer already made account

2 problems
- there should never be such an augly warning I think
- the customer is unable to create an account - after HO Customer created the account from anonymous (the customer does not know he has an account and might try and create it some time later)

Please verify

![image](https://cloud.githubusercontent.com/assets/652395/9679949/5c63e4c4-52f3-11e5-91d4-544793eb9165.png)
rror

**Comment by paales** [comment]
Does this solve the issue? https://github.com/ho-nl/Ho_Customer/commit/4b3823e629f74ea9ca2c98cd2d2b08c99c4370ee

**Comment by seansan** [comment]
You mean test it first by changing manually?

**Comment by paales** [comment]
@seansan Just update the module to see if this fixes the problem

**Comment by seansan** [comment]
OK

and thanks!

**Comment by seansan** [comment]
Yes solves it. User can create account.
