### ISSUE TITLE
Moving settings under config->customer

### ISSUE THREAD

**Issue by seansan** [ho-nl/Ho_Customer#4]
Hi, would it not be logical to move the settings related to customer and accounts creation to under config->customer configuration

Somewhere here

![image](https://cloud.githubusercontent.com/assets/652395/9680133/e78a41f0-52f4-11e5-836e-274aeb70c789.png)

**Comment by paales** [comment]
@seansan Might be a good idea for only one H&O module, but we keep our module configuration centralized

**Comment by seansan** [comment]
I understand why companies do this ...

but as this is "just an extension" I would move it

And also I really think it belongs under customer

**Comment by paales** [comment]
@seansan Agreed, if you could create a pullrequest to change this, we'll accept.

**Comment by seansan** [comment]
Is this issue open or closed? I think we should still move it ... and I understand you want a pull - who knows it will come
