### ISSUE TITLE
How can one run the backwards updating of customer records only once?

### ISSUE THREAD

**Issue by seansan** [ho-nl/Ho_Customer#5]
How can one run the backwards updating of customer records only once?

We dont really see the need to schedule a cron for this - that will the first time update all existing customers .... and after that never again

**Comment by paales** [comment]
@seansan Just set the schedule (it will batch update the customers), and disable when it's done.

**Comment by seansan** [comment]
Yes I undestand

Just a possible improvement: creating a cron job might in this case be a
little too elaborate

**Comment by paales** [comment]
@seansan Cron works just fine, we had shops where 200k customers needed to be created, which can't be done using a single action.
